analisis_economico/urls.py
# -*- coding: utf-8 -*-
"""analisis_economico URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


admin.site.site_title = "Sitio Administrativo"
admin.site.site_header = "Administración"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ficha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

ficha/urls.py
from django.conf.urls import url
from .views import *
from django.views.generic import TemplateView

urlpatterns =  [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    #url(r'^consultar/', consulta_herramienta, name='linea-consulta'),
    #url(r'^consultar-establecimiento/', consulta_establecimiento, name='consulta-establecimiento'),
    url(r'^entrevistados-autocomplete/',
        EntrevistadosAutocomplete.as_view(),
        name='entrevistados-autocomplete',),
    url(
        r'^departamento-autocomplete/',
        DepartamentoAutocomplete.as_view(create_field='nombre'),
        name='depart-autocomplete',
    ),
    url(
        r'^municipio-autocomplete/',
        MunicipioAutocomplete.as_view(create_field='nombre'),
        name='municipio-autocomplete',
    ),
    url(
        r'^comunidad-autocomplete/',
        ComunidadAutocomplete.as_view(create_field='nombre'),
        name='comunidad-autocomplete',
    ),
    url(r'^consultar/', consulta_ficha, name='linea-consulta'),
    url(r'^api/productor/', get_productor, name='productor-search'),
    url(r'^ajax/load-departamentos/', load_departamentos, name='ajax_load_departamentos'),
    url(r'^ajax/load-municipios/', load_municipios, name='ajax_load_municipios'),
    url(r'^ajax/load-comunidad/', load_comunidades, name='ajax_load_comunidad'),
    #url(r'^mapaherramienta/', obtener_lista_mapa_cacao, name='obtener-lista-mapa-cacao'),
    url(r'^(?P<vista>\w+)/$', get_view, name='get-view'),
]

ficha/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User

from lugar.models import Pais, Departamento, Municipio, Comunidad
from .choices_static import *
from multiselectfield import MultiSelectField
from djmoney.money import Money
from djmoney.contrib.exchange.models import convert_money
from configuracion.models import LineaTiempoCostos

# Create your models here.

@python_2_unicode_compatible
class OrganizacionApoyo(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Organización de apoyo'
        verbose_name_plural = 'Organizaciones de apoyos'
        unique_together = ('nombre',)

@python_2_unicode_compatible
class Entrevistados(models.Model):
    nombre = models.CharField('Nombre dueño/a de la finca', max_length=250)
    #nombre_finca = models.CharField('Nombre de la finca', max_length=250)
    sexo = models.IntegerField(choices=CHOICE_SEXO)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE,
                                    verbose_name='Departamento/Provincia')
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    comunidad = models.ForeignKey(Comunidad, on_delete=models.CASCADE, null=True, blank=True)
    latitud = models.FloatField(null=True, blank=True)
    longitud = models.FloatField(null= True, blank=True)
    altitud = models.FloatField('Altura de la finca', null=True,blank=True,
                                                    help_text='en msnm')
    maneja = models.IntegerField(choices=CHOICE_MANEJA_FINCA,
                                                          verbose_name='Quién maneja la parcela')
    organizacion_apoyo = models.ForeignKey(OrganizacionApoyo, on_delete=models.CASCADE,
                                                                                verbose_name='Organización de apoyo',
                                                                                null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Productores/as'
        verbose_name_plural = 'Productores/as'


@python_2_unicode_compatible
class Encuestadores(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Técnico'
        verbose_name_plural = 'Técnicos'
        unique_together = ('nombre',)

@python_2_unicode_compatible
class Encuesta(models.Model):
    fecha = models.DateField()
    encuestador = models.ForeignKey(Encuestadores, on_delete=models.CASCADE,
                                                                    verbose_name='Técnico')
    entrevistado = models.ForeignKey(Entrevistados, on_delete=models.CASCADE,
                                                                    verbose_name='Productor')
    modelo = models.ForeignKey(LineaTiempoCostos, on_delete=models.CASCADE)

    year = models.IntegerField(editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.year = self.fecha.year
        super(Encuesta, self).save(*args, **kwargs)

    def __str__(self):
        return u'%s' % (self.entrevistado.nombre)

    class Meta:
        verbose_name_plural = 'ENCUESTAS'

class Preguntas1(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    valoracion = models.IntegerField(choices=CHOICE_VALORACION_SUELO,
                                                            verbose_name='3. Valoración de suelo')
    manejo = models.IntegerField(choices=CHOICE_TIPO_MANEJO,
                                                            verbose_name='4. tipo de manejo')
    intensidad = models.IntegerField(choices=CHOICE_INTENSIDAD_MANEJO,
                                                            verbose_name='5. Intensidad de manejo')
    tamanio =models.IntegerField(choices=CHOICE_TAMANO_PARCELA,
                                                            verbose_name='6. Tamaño de parcela')

    class Meta:
        verbose_name_plural = 'Preguntas'


class Preguntas2(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    tipo_sistema = models.IntegerField(choices=CHOICE_TIPO_SISTEMA_AGROFORESTAL,
                                                            verbose_name='7. Tipo de sistema agroforestal')
    descripcion = models.IntegerField(choices=CHOICE_DESCRIPCION_SISTEMA_AGRO,
                                                            verbose_name='8. Descripción de sistema agroforestal')
    riego = models.IntegerField(choices=CHOICE_RIEGO,
                                                            verbose_name='9. Riego')

    class Meta:
        verbose_name_plural = 'Preguntas'

class Preguntas3(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    area = models.FloatField('Área de la parcela')
    unidad = models.IntegerField(choices=CHOICE_UNIDAD_TIERRA)
    pendiente = models.IntegerField(choices=CHOICE_PENDIENTE)

    area_ha = models.FloatField(editable=False, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.unidad == 1:
            self.area_ha = self.area / 1.4
        if self.unidad == 2:
            self.area_ha = self.area / 1
        if self.unidad == 3:
            self.area_ha = self.area / 16.0
        if self.unidad == 4:
            self.area_ha = float(self.area) / 10000
        if self.unidad == 5:
            self.area_ha = self.area / 24.0

        super(Preguntas3, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Área de parcela y inclinación'

@python_2_unicode_compatible
class CacaoClonesVariedad(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Cacao Clones o Variedad'

@python_2_unicode_compatible
class CafeClonesVariedad(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Café Clones o Variedad'

@python_2_unicode_compatible
class TipoMusaceas(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Tipo Musaceas'

@python_2_unicode_compatible
class EspeciesFrutales(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Especies de frutales'

@python_2_unicode_compatible
class EspeciesMaderables(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Especies Maderables'

@python_2_unicode_compatible
class ArbolesServicios(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Árboles de Servicios'

@python_2_unicode_compatible
class GranosBasicos(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Granos básicos'

class InventarioCacao(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    clon = models.ForeignKey(CacaoClonesVariedad, on_delete=models.CASCADE)
    cantidad = models.FloatField()
    edad = models.FloatField()

    class Meta:
        verbose_name_plural = 'Cacao'

class InventarioCafe(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    clon = models.ForeignKey(CafeClonesVariedad, on_delete=models.CASCADE)
    cantidad = models.FloatField()
    edad = models.FloatField()

    class Meta:
        verbose_name_plural = 'Café'

class InventarioMusaceas(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    clon = models.ForeignKey(TipoMusaceas, on_delete=models.CASCADE, verbose_name='Tipo')
    cantidad = models.FloatField()
    edad = models.FloatField()

    class Meta:
        verbose_name_plural = 'Musaceas'

class InventarioFrutales(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    clon = models.ForeignKey(EspeciesFrutales, on_delete=models.CASCADE, verbose_name='Especies')
    cantidad = models.FloatField()
    edad = models.FloatField()

    class Meta:
        verbose_name_plural = 'Frutales'

class InventarioMaderables(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    clon = models.ForeignKey(EspeciesMaderables, on_delete=models.CASCADE, verbose_name='Especies')
    cantidad = models.FloatField()
    edad = models.FloatField()

    class Meta:
        verbose_name_plural = 'Maderables'

class InventarioArboles(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    clon = models.ForeignKey(ArbolesServicios, on_delete=models.CASCADE, verbose_name='Especies')
    cantidad = models.FloatField()
    edad = models.FloatField()

    class Meta:
        verbose_name_plural = 'Árboles de servicios'

class InventarioGranosBasicos(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    clon = models.ForeignKey(GranosBasicos, on_delete=models.CASCADE, verbose_name='Tipo')
    cantidad = models.FloatField()
    edad = models.FloatField()

    class Meta:
        verbose_name_plural = 'Granos básicos'

templates/ficha/consulta_ficha.html
{% extends "base.html" %}

{% block content %}
  <section class="jumbotron">
    <div class="container">
      <div class="btn-group">
            <ol class="breadcrumb hide-phone p-0 m-0">
                <li class="breadcrumb-item">
                    <a href="/">Inicio</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'linea-consulta' %}">Consultar</a>
                </li>
            </ol>
        </div>
    </div>
  </section>

  <div class="py-5 bg-light">
    <div class="container">
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="header-title mb-4">Formulario de consulta</h4>
            <div class="row">
                 {%if centinela == 1 %}
                    {% include "ficha/menu.html" %}
                {%endif%}
                <div class="col-md-10 mx-auto">
                <form action="." method="POST">{% csrf_token %}
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label for="fecha">Fecha</label>
                        {{form.fecha}}
                    </div>
                    <div class="col-sm-6">
                        <label for="municipio">Pais</label>
                        {{form.pais}}
                    </div>
                </div>
                <div class="form-group row">
                <div class="col-sm-6">
                        <label for="organizacion">Modelo</label>
                        {{form.modelo}}
                    </div>
                    <div class="col-sm-6">
                        <label for="comunidad">Tipo de manejo</label>
                        {{form.manejo}}
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label for="pais">Tamaño de la parcela</label>
                        {{form.parcela}}
                    </div>
                    <div class="col-sm-6">
                        <label for="sexo">Intensidad de manejo</label>
                        {{form.intensidad}}
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label for="departamento">Riego</label>
                        {{form.riego}}
                    </div>
                        <div class="col-sm-6">
                            <label for="productor">sexo</label>
                            {{form.sexo}}
                        </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label for="departamento">Tipo SAF</label>
                        {{form.saf}}
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="col-sm-6">
                            <label for="productor">Productor</label>
                            {{form.productor}}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label for="departamento">Valoración de suelo</label>
                        {{form.valoracion}}
                    </div>
                </div>
                 <div class="d-flex justify-content-center">
                    <input type="submit" value="Consultar" id="boton" class="btn btn-success center-block"/>
                </div>
            </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock content %}

{% block extra_js %}
<link href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" rel="stylesheet" />
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function () {
    // Select2
    $(".select2").select2();
    $('#id_fecha').select2();
});

$("#id_productor").autocomplete({
    source: '{% url "productor-search"%}',
    minLength: 2,
  });

$('.botonera').slideDown('slow');

$("#id_pais").change(function () {
      var url = '/ajax/load-departamentos/'
      var paisId = $("#id_pais").val();

    $.ajax({
        url: url,
        data: {
          'pais': paisId
        },
        success: function (data) {
          $("#id_departamento").html(data);
        }
    });
 });

$("#id_departamento").change(function () {
      var url = '/ajax/load-municipios/'
      var departamentoId = $("#id_departamento").val();

    $.ajax({
        url: url,
        data: {
          'departamento': departamentoId
        },
        success: function (data) {
          $("#id_municipio").html(data);
        }
    });
 });

$("#id_municipio").change(function () {
      var url = '/ajax/load-comunidad/'
      var municipioId = $("#id_municipio").val();

    $.ajax({
        url: url,
        data: {
          'municipio': municipioId
        },
        success: function (data) {
          $("#id_comunidad").html(data);
        }
    });
 });

</script>
{% endblock extra_js %}

templates/ficha/consulta_form.html
<form action="." method="POST">{% csrf_token %}
                <div class="form-group">
                        <label for="fecha">Fecha</label>
                        {{form.fecha}}
                </div>
                <div class="form-group">
                        <label for="municipio">Pais</label>
                        {{form.pais}}
                </div>
                <div class="form-group">
                        <label for="organizacion">Modelo</label>
                        {{form.modelo}}
                </div>
                <div class="form-group">
                        <label for="comunidad">Tipo de manejo</label>
                        {{form.manejo}}
                </div>
                <div class="form-group">
                        <label for="pais">Tamaño de la parcela</label>
                        {{form.parcela}}
                </div>
                <div class="form-group">
                        <label for="sexo">Intensidad de manejo</label>
                        {{form.intensidad}}
                </div>
                <div class="form-group">
                        <label for="departamento">Riego</label>
                        {{form.riego}}
                </div>
                <div class="form-group">
                            <label for="productor">sexo</label>
                            {{form.sexo}}
                </div>
                <div class="form-group">
                        <label for="departamento">Tipo SAF</label>
                        {{form.saf}}
                </div>
                <div class="form-group">
                    <label for="departamento">Valoración de suelo</label>
                        {{form.valoracion}}
                </div>
                <div class="form-group">
                    {% if request.user.is_authenticated %}
                            <label for="productor">Productor</label>
                            {{form.productor}}
                    {% endif %}
                </div>
                 <div class="">
                    <input type="submit" value="Consultar" id="boton" class="btn btn-success"/>
                </div>
            </form>

templates/ficha/lugares_dropdown_list_options.html
<option value="">---------</option>
{% for obj in lugares %}
<option value="{{ obj.pk }}">{{ obj.nombre }}</option>
{% endfor %}

templates/ficha/rentabilidad_saf.html
{% extends "base.html" %}

{% load tools %}
{% load humanize %}

{% block content %}
<style type="text/css">

</style>
  <section class="jumbotron text-center">
    <div class="container">
        <div class="btn-group">
            <ol class="breadcrumb hide-phone p-0 m-0">
                <li class="breadcrumb-item">
                    <a href="/">Inicio</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'linea-consulta' %}">Consultar</a>
                </li>
            </ol>
        </div>
    <p>Numero de familas {{num_familias}}</p>

        <span class="navbar-text">
           <div id="mas" class="btnindicador">
                <a href="">
                    <span id="estado">
                    <span><i class="fa fa-arrow-down"></i></span>
                    </span> Cambiar de Indicador
                </a>
            </div>
        </span>

      <div class="row">
        <div id="mostrar">
            {% include "ficha/menu.html" %}
        </div>
    </div>

    </div>
  </section>

  <section>
<div class="container">
    <div class="row">
        <div class="col-sm-3 px-1">
            <div class="py-2 sticky-top flex-grow-1">
                {% include "ficha/consulta_form.html" %}
            </div>
        </div>
        <div class="col" id="main">
            {% include "ficha/filtros.html" %}
                <ul>
                    <li>Número de parcelas: <strong>{{numero_total_parcela}}</strong></li>
                    <li>Areas de las parcelas (ha) total: <strong>{{promedio_areas|floatformat:2}}</strong> </li>
                </ul>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="parcela-tab" data-toggle="tab" href="#parcela" role="tab" aria-controls="parcela" aria-selected="true">Inversión</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="riego-tab" data-toggle="tab" href="#riego" role="tab" aria-controls="riego" aria-selected="false">Ingreso neto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="valoracion-tab" data-toggle="tab" href="#valoracion" role="tab" aria-controls="valoracion" aria-selected="false">Finanzas</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="parcela" role="tabpanel" aria-labelledby="parcela-tab">

                    <div class="col6">
                        <h4 class="title line-bottom mb-10">
                        Inversión proyectada por $/ha por años
                        </h4>
                        <div class="table-responsive">
                        <table class="table table-bordered table-striped mb-0">
                            <thead class="bg-theme-colored-darker3">
                                <tr>
                                    <th>Año</th>
                                    <th>Cacao</th>
                                    <th>Café</th>
                                    <th>Musaceas</th>
                                    <th>Frutales</th>
                                    <th>Maderables</th>
                                    <th>Árboles de servicios</th>
                                    <th>Granos básicos</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for k,v  in modelado_inversion.items %}
                               <tr>
                                   <td>{{k}}</td>
                                    <td>{{v.0|floatformat:2}}</td>
                                    <td>{{v.1|floatformat:2}}</td>
                                    <td>{{v.2|floatformat:2}}</td>
                                    <td>{{v.3|floatformat:2}}</td>
                                    <td>{{v.4|floatformat:2}}</td>
                                    <td>{{v.5|floatformat:2}}</td>
                                    <td>{{v.6|floatformat:2}}</td>
                                    <td>{{v.7|floatformat:2}}</td>
                               </tr>
                               {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    </div>


      </div>
      <div class="tab-pane fade" id="riego" role="tabpanel" aria-labelledby="riego-tab">


                    <div class="col6">
                        <h4 class="title line-bottom mb-10">
                        Ingreso neto proyectado por $/ha por años
                        </h4>
                        <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <thead class="bg-theme-colored-darker3">
                                <tr>
                                    <th>Año</th>
                                    <th>Cacao</th>
                                    <th>Café</th>
                                    <th>Musaceas</th>
                                    <th>Frutales</th>
                                    <th>Maderables</th>
                                    <th>Árboles de servicios</th>
                                    <th>Granos básicos</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for k,v  in modelado_ingreso.items %}
                               <tr>
                                   <td>{{k}}</td>
                                    <td>{{v.0|floatformat:2}}</td>
                                    <td>{{v.1|floatformat:2}}</td>
                                    <td>{{v.2|floatformat:2}}</td>
                                    <td>{{v.3|floatformat:2}}</td>
                                    <td>{{v.4|floatformat:2}}</td>
                                    <td>{{v.5|floatformat:2}}</td>
                                    <td>{{v.6|floatformat:2}}</td>
                                    <td>{{v.7|floatformat:2}}</td>
                               </tr>
                               {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    </div>


      </div>
      <div class="tab-pane fade" id="valoracion" role="tabpanel" aria-labelledby="valoracion-tab">
        <div class="row">
            <div class="col-6">
            <h4 class="sub-header">Tasa Interna de retorno para 25 años con Tasa de referencia 10%</h4>
              <div class="table-responsive">
                        <table class="table table-bordered table-striped mb-0">
                            <thead class="bg-theme-colored-darker3">
                                <tr>
                                    <th>Rubros</th>
                                    <th>Porcentajes</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for k,v  in modelado_tir.items %}
                               <tr>
                                   <td>{{k}}</td>
                                    <td>{{v|floatformat:2}} %</td>
                               </tr>
                               {% endfor %}
                            </tbody>
                        </table>
                      </div>
            </div>
          <div class="col-6">
                <h4 class="sub-header">Valor Presente Neto para 25 años con Tasa de referencia 10%</h4>
                <div class="table-responsive">
                <table class="table table-bordered table-striped mb-0">
                            <thead class="bg-theme-colored-darker3">
                                <tr>
                                    <th>Rubros</th>
                                    <th>$</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for k,v  in modelado_sistema.items %}
                               <tr>
                                   <td>{{k}}</td>
                                    <td>{{v|floatformat:2|intcomma}}</td>
                               </tr>
                               {% endfor %}
                            </tbody>
                    </table>
                </div>
        </div>
    </div>


      </div>

    </div>

        </div>
    </div>
</div>
  </section>

{% endblock content %}

{% block extra_js %}
<link href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" rel="stylesheet" />
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function () {
    // Select2
    $(".select2").select2();
    $('#id_fecha').select2();
});

$("#id_productor").autocomplete({
    source: '{% url "productor-search"%}',
    minLength: 2,
  });
$('#id_nexturl').val(window.location.href);
{% if request.session.fecha %}
        $('#id_fecha').val({% for x in request.session.fecha %} {{x}} {%endfor%});
{% endif %}
{% if request.session.pais %}
        $('#id_pais').val({{request.session.pais.id}});
{% endif %}
{% if request.session.modelo %}
        $('#id_modelo').val({{request.session.modelo.id}});
{% endif %}
{% if request.session.parcela %}
        $('#id_parcela').val({{request.session.parcela}});
{% endif %}
{% if request.session.manejo %}
        $('#id_manejo').val({{request.session.manejo}});
{% endif %}
{% if request.session.intensidad %}
        $('#id_intensidad').val({{request.session.intensidad}});
{% endif %}
{% if request.session.riego %}
        $('#id_riego').val({{request.session.riego}});
{% endif %}
{% if request.session.saf %}
        $('#id_saf').val({{request.session.saf}});
{% endif %}
{% if request.session.valoracion %}
        $('#id_valoracion').val({{request.session.valoracion}});
{% endif %}
{% if request.session.sexo %}
        $('#id_sexo').val({{request.session.sexo}});
{% endif %}
</script>
<script type="text/javascript">
    var flag = true;
    $(document).ready(function(){
        $('#mas').click(function(){
            if(flag==true){
                $('.botonera').slideDown('slow');
                $('#estado').html('<span><i class="fa fa-arrow-up"></i></span>');
                flag = false;
            }else if (flag==false){
                $('.botonera').slideUp('slow');
                $('#estado').html('<span><i class="fa fa-arrow-down"></i></span>');
                flag = true;
            }
            return false;
            });
        });
</script>
{% endblock extra_js %}